version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2g'   
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
  vendor-portal:
    image: jacky/selenium:latest
    shm_size: '2g'   
    depends_on:
      - chrome
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - THREAD_COUNT=2
      - TEST_SUITE=vendor-portal.xml
    volumes:
      - C:\Users\ATUser001\git\selenium-docker-cicd\output\vendor-portal:/home/selenium-docker-cicd/test-output
  flight-reservation:
    image: jacky/selenium:latest
    shm_size: '2g'   
    depends_on:
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - THREAD_COUNT=2
      - TEST_SUITE=flight-reservation.xml
    volumes:
      - C:\Users\ATUser001\git\selenium-docker-cicd\output\flight-reservation:/home/selenium-docker-cicd/test-output